# Generated by Django 4.1.7 on 2023-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=50)),
                ('stars', models.TextField()),
                ('feature_bullets', models.TextField()),
                ('rating_count', models.TextField()),
                ('variant_data', models.TextField()),
            ],
        ),
    ]
