# Generated by Django 4.1.7 on 2023-06-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
