# Generated by Django 4.1.7 on 2023-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_com', '0002_product_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='gostring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
