# Generated by Django 4.1.7 on 2023-07-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_com', '0003_gostring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature_bullets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_data',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.TextField(blank=True),
        ),
    ]
