# Generated by Django 4.1.7 on 2023-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_com', '0005_product_onlinestore_product_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacted_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='gostring',
        ),
    ]
